#!/bin/bash

function merge {
    if [[ $# -ne 2 ]]; then
        echo "Provide the paths of 2 flight files to merge (generated by memory_efficient Python strategy)"
        return 1
    fi
    echo "Merging $1 $2"
    paste  --delimiters=LIST $1 $2 > $1.merge
    sed -i 's/\r//g' $1.merge
    mv $1.merge $1
}

merge Flights_training.csv Flights_training_dest.csv
merge Flights_test.csv Flights_test_dest.csv