#!/bin/bash

data_path=../data

function merge {
    if [[ $# -ne 2 ]]; then
        echo "Provide the paths of flight data file excluding DEST*, followed by the DEST file to be merged (generated by memory_efficient Python strategy)"
        return 1
    fi
    echo "Merging $1 $2"
    paste  --delimiters=, $1 $2 > $1.merge
    # remove carriage returns and header row (required for SageMaker CSV)
    sed -i 's/\r//g;1d' $1.merge
    mv $1.merge $1
    rm -f $2
}

merge $data_path/Flights_training.csv $data_path/Flights_training_dest.csv
merge $data_path/Flights_test.csv $data_path/Flights_test_dest.csv